### ISSUE TITLE
Date setter

### ISSUE THREAD

**Issue by gc-sommer** [geocledian/gc-map#1]
Implement a date setter method for the widget so one may synchronize other widgets for a certain date, e.g.:

`vmRoot.$children[0].setDate('2019-05-01');`

Currently changing the image of a certain date is only available in the widget by clicking on the timeline, which transforms to an index (currentRasterIndex). A change listener on that property then will load the image of that index.

**Comment by gc-sommer** [comment]
I would implement this feature in two stages:

1. the developer who embeds the widget knows which date is available in the data of the widget and sets it -> the widget sets the image to that date exactly
2. the developer who embeds the widget does not have to care about the availability and just sets an arbitiary date; the widget sets the image close as possible to the desired date

**Comment by gc-sommer** [comment]
first one implemented with commit https://github.com/geocledian/gc-map/commit/c41067de8f4085f67e1035c4d6879e381bc2dd7c

**Comment by robindecroon** [comment]
I currently added some code in my local version to address the second part in `(this.timeLine.on("timechanged")`. Maybe this can be of help? When you manually set a new date in the map, the dates did not snap to the nearest data points.

```
let days = parcel.timeseries.map(r => new Date(r.date));
let testDate = a.time;
let closestDate = days.length;
let bestDiff = -(new Date(0, 0, 0)).valueOf();
let currDiff = 0;
let i;

for (i = 0; i < days.length; ++i) {
  currDiff = Math.abs(days[i] - testDate);
  if (currDiff < bestDiff) {
    closestDate = i;
    bestDiff = currDiff;
  }
}

r = closestDate;
if (r >= 0) {
  this.currentRasterIndex = r;
}
```

**Comment by gc-sommer** [comment]
Hi @robindecroon ,
thank you for the code - I will check this locally and commit it in the master branch afterwards!

in the long run it may be better to adjust the API for searching the closest date to a certain date & product.

best regards,
Johannes

**Comment by gc-sommer** [comment]
Hi @robindecroon,
sorry for the delay.  Snapping for external date is also implemented now with commit https://github.com/geocledian/gc-map/commit/e9f76c17c24c3b6f0a570abe61dccbe4e55a61b8

Best regards,
Johannes
